// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425215857_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Domain.Entities.ItemCardapio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItensCardapio");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Categoria = 1,
                            Nome = "X Burger",
                            Preco = 5.00m
                        },
                        new
                        {
                            Id = new Guid("da2fd609-6684-488b-830c-8f84830e0471"),
                            Categoria = 1,
                            Nome = "X Egg",
                            Preco = 4.50m
                        },
                        new
                        {
                            Id = new Guid("1176047c-658b-49fc-9168-96144b202457"),
                            Categoria = 1,
                            Nome = "X Bacon",
                            Preco = 7.00m
                        },
                        new
                        {
                            Id = new Guid("22f462a7-5827-4638-89c0-141a20689b94"),
                            Categoria = 2,
                            Nome = "Batata frita",
                            Preco = 2.00m
                        },
                        new
                        {
                            Id = new Guid("79402543-5242-4f36-963d-4959146f338d"),
                            Categoria = 3,
                            Nome = "Refrigerante",
                            Preco = 2.50m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalFinal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ItemCardapioPedido", b =>
                {
                    b.Property<Guid>("ItensId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PedidosId")
                        .HasColumnType("TEXT");

                    b.HasKey("ItensId", "PedidosId");

                    b.HasIndex("PedidosId");

                    b.ToTable("PedidoItens", (string)null);
                });

            modelBuilder.Entity("ItemCardapioPedido", b =>
                {
                    b.HasOne("Domain.Entities.ItemCardapio", null)
                        .WithMany()
                        .HasForeignKey("ItensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
